name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Selenium Tests
        run: |
          pip install -r requirements.txt
          pytest ui-testing/selenium-python/ --alluredir=allure-results
